### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by losfair** [losfair/wasm-core#1]
- [ ] Port parity-wasm to be no_std compatible
- [ ] Interpreter: Bytecode parsing
- [ ] Interpreter: Execution
- [ ] Integration: General platforms e.g. Windows/Linux/macOS
- [ ] Integration: Linux kernel
- [ ] Integration: STM32
